<a href="https://colab.research.google.com/github/Pritham041/Deep-learning/blob/main/linearRegression_iris_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns

In [3]:
df = sns.get_dataset_names()
df

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [4]:
df = sns.load_dataset('iris')

In [5]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [6]:
df.shape

(150, 5)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [8]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [9]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [10]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [11]:
df.duplicated().sum()

1

In [12]:
df.drop_duplicates(keep='first', inplace=True)

In [13]:
df.duplicated().sum()

0

In [14]:
df['species'].value_counts()

species
setosa        50
versicolor    50
virginica     49
Name: count, dtype: int64

In [15]:
from sklearn.preprocessing import LabelEncoder

In [16]:
le = LabelEncoder()

In [17]:
df['species'] = le.fit_transform(df['species'])

In [18]:
df['species'].value_counts()

species
0    50
1    50
2    49
Name: count, dtype: int64

In [19]:
x = df.drop('species', axis=1)
y = df['species']

In [20]:
print(x)

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[149 rows x 4 columns]

In [21]:
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: species, Length: 149, dtype: int64

In [22]:
#train test split
from sklearn.model_selection import train_test_split

In [23]:
X_train,X_test,y_train,y_test = train_test_split(x,y, test_size=0.2, random_state=42)

In [24]:
X_test

     sepal_length  sepal_width  petal_length  petal_width
73            6.1          2.8           4.7          1.2
18            5.7          3.8           1.7          0.3
117           7.7          3.8           6.7          2.2
78            6.0          2.9           4.5          1.5
76            6.8          2.8           4.8          1.4
31            5.4          3.4           1.5          0.4
64            5.6          2.9           3.6          1.3
140           6.7          3.1           5.6          2.4
68            6.2          2.2           4.5          1.5
82            5.8          2.7           3.9          1.2
109           7.2          3.6           6.1          2.5
12            4.8          3.0           1.4          0.1
36            5.5          3.5           1.3          0.2
9             4.9          3.1           1.5          0.1
19            5.1          3.8           1.5          0.3
56            6.3          3.3           4.7          1.6
136           6.3          3.4           5.6          2.4
69            5.6          2.5           3.9          1.1
55            5.7          2.8           4.5          1.3
131           7.9          3.8           6.4          2.0
29            4.7          3.2           1.6          0.2
123           6.3          2.7           4.9          1.8
26            5.0          3.4           1.6          0.4
127           6.1          3.0           4.9          1.8
128           6.4          2.8           5.6          2.1
145           6.7          3.0           5.2          2.3
110           6.5          3.2           5.1          2.0
101           5.8          2.7           5.1          1.9
45            4.8          3.0           1.4          0.3
30            4.8          3.1           1.6          0.2

In [25]:
from sklearn.linear_model import LinearRegression

In [26]:
lr = LinearRegression()

In [27]:
lr_model = lr.fit(X_train,y_train)

In [28]:
pred = lr_model.predict(X_test)

In [29]:
pred

array([ 1.22109218, -0.02811   ,  2.05381668,  1.34258346,  1.28081007,
        0.02774163,  1.05040717,  2.0289857 ,  1.35321414,  1.05796007,
        2.13221294, -0.07947   , -0.14788967, -0.06984645, -0.01340846,
        1.39695081,  2.05833351,  1.0336274 ,  1.26932805,  1.84698667,
        0.02724932,  1.5847987 ,  0.0959039 ,  1.59257135,  1.90982246,
        1.87842921,  1.70046228,  1.74386999,  0.03074898,  0.02106257])

In [30]:
y_test.head(2)

73    1
18    0
Name: species, dtype: int64

In [31]:
pred.astype(int)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 0])

In [34]:
from sklearn.metrics import mean_squared_error

mse = mean_squared_error(y_test, pred)
print(f"Mean Squared Error (MSE): {mse}")

Mean Squared Error (MSE): 0.04059306932128771